import { defineConfig } from 'orval';

export default defineConfig({
  vantage: {
    input: {
      target: 'http://localhost:8000/openapi.json',
    },
    output: {
      target: 'packages/shared/src/generated',
      client: 'react-query',
      baseUrl: 'http://localhost:8000',
      httpClient: 'fetch',
      mode: 'split',
      override: {
        query: {
          useQuery: true,
          useMutation: true,
          useInfinite: false,
          options: {
            staleTime: 5 * 60 * 1000, // 5 minutes
            refetchOnWindowFocus: false,
          },
        },
        operationName: (operation, route, verb) => {
          // Use clean operation IDs from FastAPI directly!
          const operationId = operation.operationId || '';
          
          // Simply capitalize the first letter for PascalCase
          return operationId.charAt(0).toUpperCase() + operationId.slice(1);
        },
        header: () => [
          '// 🚀 Auto-generated by Orval',
          '// 🔄 Do not edit manually - regenerate with: pnpm generate-types',
          '',
        ],
      },
    },
  },
}); 