import { defineConfig } from 'orval';

export default defineConfig({
  vantage: {
    input: {
      target: 'http://localhost:8000/openapi.json',
    },
    output: {
      target: 'packages/shared/src/generated',
      client: 'react-query',
      baseUrl: 'http://localhost:8000',
      httpClient: 'fetch',
      mode: 'split',
      override: {
        query: {
          useQuery: true,
          useMutation: true,
          useInfinite: false,
          options: {
            staleTime: 5 * 60 * 1000, // 5 minutes
            refetchOnWindowFocus: false,
          },
        },
        header: () => [
          '// 🚀 Auto-generated by Orval',
          '// 🔄 Do not edit manually - regenerate with: pnpm generate-types',
          '',
        ],
      },
    },
  },
}); 