"""Add user fields and barangay table

Revision ID: 5f9b4e3b7a2d
Revises: 92831e959bbb
Create Date: 2025-07-16 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9b4e3b7a2d'
down_revision: Union[str, Sequence[str], None] = '92831e959bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barangays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barangays_id'), 'barangays', ['id'], unique=False)
    op.create_index(op.f('ix_barangays_name'), 'barangays', ['name'], unique=True)
    
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default=sa.text("'BLGU User'")))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('users', sa.Column('barangay_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'barangays', ['barangay_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'barangay_id')
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone_number')

    op.drop_index(op.f('ix_barangays_name'), table_name='barangays')
    op.drop_index(op.f('ix_barangays_id'), table_name='barangays')
    op.drop_table('barangays')
    # ### end Alembic commands ### 