// This file is auto-generated by running: pnpm generate-types
// Do not edit manually - it will be overwritten

// Placeholder types - run 'pnpm generate-types' to generate real types from FastAPI
export interface ApiResponse {
  message: string;
  status: string;
  data?: any;
}

export interface User {
  id: string;
  email: string;
  name: string;
  created_at: string;
}

export interface HealthCheck {
  status: string;
  timestamp: string;
} 