"""Add relationship between users and governance_areas

Revision ID: 10d9f89f28ac
Revises: 52cc77e65cc7
Create Date: 2025-07-21 16:09:37.510955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d9f89f28ac'
down_revision: Union[str, Sequence[str], None] = '52cc77e65cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('governance_area_id', sa.SmallInteger(), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_foreign_key(None, 'users', 'governance_areas', ['governance_area_id'], ['id'])
    op.drop_column('users', 'assessor_area')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('assessor_area', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'governance_area_id')
    # ### end Alembic commands ###
