"""Initial database schema

Revision ID: 421de4cd5e1e
Revises:
Create Date: 2025-07-29 10:34:18.284880

"""

from typing import Sequence, Union

# Removed unused imports - this migration has no operations


# revision identifiers, used by Alembic.
revision: str = "421de4cd5e1e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
