"""Add intelligence fields to assessments

Revision ID: 9feee8a18b32
Revises: ec084313d881
Create Date: 2025-10-28 13:00:09.005814

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9feee8a18b32"
down_revision: Union[str, Sequence[str], None] = "ec084313d881"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Manually create the enum type
    compliance_status_enum = sa.Enum("PASSED", "FAILED", name="compliance_status_enum")
    compliance_status_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assessments",
        sa.Column(
            "final_compliance_status",
            sa.Enum(
                "PASSED",
                "FAILED",
                name="compliance_status_enum",
                create_constraint=False,
            ),
            nullable=True,
        ),
    )
    op.add_column("assessments", sa.Column("area_results", sa.JSON(), nullable=True))
    op.add_column(
        "assessments", sa.Column("ai_recommendations", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assessments", "ai_recommendations")
    op.drop_column("assessments", "area_results")
    op.drop_column("assessments", "final_compliance_status")
    # ### end Alembic commands ###

    # Manually drop the enum type
    compliance_status_enum = sa.Enum(name="compliance_status_enum")
    compliance_status_enum.drop(op.get_bind())
