"""Add rework_count field to assessments table

Revision ID: ec084313d881
Revises: ee9817766282
Create Date: 2025-10-19 14:42:48.694712

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec084313d881"
down_revision: Union[str, Sequence[str], None] = "ee9817766282"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value for existing records
    op.add_column(
        "assessments",
        sa.Column("rework_count", sa.Integer(), nullable=False, server_default="0"),
    )
    # Remove server default after column is created
    op.alter_column("assessments", "rework_count", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assessments", "rework_count")
    # ### end Alembic commands ###
