"""Add validation_status to assessment_responses table

Revision ID: ee9817766282
Revises: 93aa637add7b
Create Date: 2025-10-18 07:42:55.898591

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee9817766282"
down_revision: Union[str, Sequence[str], None] = "93aa637add7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    validation_status_enum = sa.Enum(
        "PASS", "FAIL", "CONDITIONAL", name="validation_status_enum"
    )
    validation_status_enum.create(op.get_bind())

    # Add the column using the created enum type
    op.add_column(
        "assessment_responses",
        sa.Column("validation_status", validation_status_enum, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assessment_responses", "validation_status")
    # Drop the enum type
    validation_status_enum = sa.Enum(
        "PASS", "FAIL", "CONDITIONAL", name="validation_status_enum"
    )
    validation_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
