"""Fix governance_areas id column to auto-increment

Revision ID: f5892d7aa0ea
Revises: de8ece1d7614
Create Date: 2025-10-18 07:26:37.078465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5892d7aa0ea'
down_revision: Union[str, Sequence[str], None] = 'de8ece1d7614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
